### ISSUE TITLE
Can't render emoticons!

### ISSUE THREAD

**Issue by Chisha14** [ealush/emoji-picker-textfields-component#8]
Below is my code, I don't think I am writing it correctly to be able to view emoticons, I get the code of the emoticons inside the textbox such as :happy: and not the icon. Where I am mistaken!!!

`import React, { Component } from 'react'
import {VERIFY_USER} from './Events' 
import EmojiField from 'emoji-picker-textfield';

export default class LoginForm extends Component {

	constructor(props){
		super(props);
		this.state={
			nickname:"",
			error:""
		};
		this.getUnicode = this.getUnicode.bind(this);
		this.getImages = this.getImages.bind(this);
	}
	
	setUser=({user, isUser}) =>{
		console.log(user,isUser)
		if(isUser)
			this.setError("Username taken")
		else{
			this.props.setUser(user)
			this.setError("")
		}
	}
	componentDidMount(){
		this.getUnicode();
		this.getImages();
	}
	setError=(error)=>{
		this.setState({error})
	}

	handleSubmit = (e)=>{
		e.preventDefault()
		const {socket} = this.props
		const {nickname} = this.state
		socket.emit(VERIFY_USER, nickname, this.setUser)
	}

	handleChange = (e)=>{
		this.setState({nickname:e.target.value})
	}

	getImages(){
		return this._field.getImages();
	}
	getUnicode(){
		return this._field.getUnicode();
	}
	onChange(e, value) {
		document.getElementById('nickname').value =value;
	}

	render() {
		const { nickname, error } = this.state; 
		return(
			<div>
				<form onSubmit={this.handleSubmit}>
					<label>
						<h2>Got a nickname</h2>
					</label>
					<EmojiField
						id="emoji"
						name="my-input" 
						onChange={this.onChange}
					 	ref={(_field) => {this._field = _field; }}
					 	fieldType="input"
					 />
					<input
						ref={(input)=>{this.textInput = input}}
						type="text"
						name="my-input"
						id="nickname"
						value={nickname}
						onChange={this.handleChange}
						placeholder={"Username"}
					/>
					
					<div className="error">{error ? error:null}</div>
				</form>
				
			</div>
		);
	}

}`

please help @ealush

**Comment by ealush** [comment]
Hey, @Chisha14, thanks for reaching out.

Please help me make sure I understand correctly what you are trying to achieve:

1. Are you trying to show the actual unicode emojis within your textfield so you see 😂  instead of `:joy:` as the value of the input.
This is currently intentionally not supported, as it is not consistently supported among browsers and operating systems. Older operating systems support a narrow set of emojis, and instead of seeing the actual emoji, you would see either a square, or some other form of encoded value.

Here is how I see the `:clown_face:` emoji on my mac:
![image](https://user-images.githubusercontent.com/11255103/30850398-1a0ce76c-a2ae-11e7-80e4-312fbfb0ed1e.png)
Here is how Github shown is on a windows machine running IE11:
![image](https://user-images.githubusercontent.com/11255103/30850451-424f1fa6-a2ae-11e7-94ea-37b7c7b5fcf1.png)
And here is what I get if I try to paste the actual emoji character to the this comment textarea on that machine: 
![image](https://user-images.githubusercontent.com/11255103/30850519-68977d5c-a2ae-11e7-9bc6-d28802a99c47.png)
And here I am trying to put the actual character on my mac: 🤡 , which may look completely different on your end.

To allow a consistent behavior among all operating systems and to prevent bugs resulting from lack of OS support, I simply show the colonized name, as slack do in their textarea, and as github do on windows machines.

2. You are ok with seeing the emoji name in the text field, but want to get the emoji image/character to display later on when viewing the output of the input:
Here you did the first part correctly, by using either the `getImages` or `getUnicode` method, now you need to actually use this value you receive and keep it in the state (or do whatever with it, actually) , to get the desired output.

I hope that helps :)

**Comment by Chisha14** [comment]
Hi again, yes you are helping me a lot, much appreciated my problem resides in what you said in "2": "use this value you receive and keep it in the state (or do whatever with it, actually) , to get the desired output."
what do you mean exactly, can you provide me a simple example if you please @ealush ?

**Comment by ealush** [comment]
Sure.

In your onChange function, when you get `value`, you simply get the the raw value of your textfield, no emoji manipulations. To get the unicoded value, your onChange needs to look somewhat like this:
```js
onChange(e, value) {
   conts unicodeValue = this._field.getUnicode();
   // unicodeValue now holds the actual emoji content you need
   // and you can use it in any manner you wish
   // ...
}
```

Also, two things to note:
1. I see that you try to set the nickname field value by directly updating the value of the DOM element. Usually, in react, you would want to do it by updating its value in the state.
2. Both inputs share the same `onChange` functions. This means that whenever your `nickname` field changes, you will update it again, possibly with nothing, since you won't always get the value param (only the emoji text field has it). I would either break it into two different onChange handlers, or add an `if/else` statement in the onChange function that handles each field differently.

**Comment by Chisha14** [comment]
`	onChange(e, val) {
		const unicodeValue = this._field.getUnicode();
		alert (unicodeValue)
	}
`
this is my onChange, I am getting error regarind this._field.getUnicode
**error: TypeError: this._field is undefined**

**Comment by Chisha14** [comment]
by the way you're right regarding what you said, in the end it is just a testing project ... Thanks a lot for your time :) and your suggestions :+1:

**Comment by ealush** [comment]
hrm. Looks like `this` is not accessible from your onChange  function. 
Try to add the following line inside your constructor:
```
this.onChange = this.onChange.bind(this);
```

and, no problem :)

**Comment by Chisha14** [comment]
Merciiiiiiiiiiiiiiiiiiii, Graciassssssssssssssss, Arigatoooooooooooo, Thankssssssssssssssssssssss a lottttttttttt really, big thanks for your time :+1:  you're really a kind, gentleman :)

**Comment by ealush** [comment]
Anytime :)

**Comment by Chisha14** [comment]
Sorry again @ealush for disturbing, but do you have a solution for the following:
suppose I clicked on emoji icon and choose the :laughing:  emoticons, I want now to null the value of the textarea that supports the unicode of emoticons I did it using the following, that after I clicked a button "send" I run document.getElementById('emoji').value="", the textarea that is bounded to the emoticons list is empty, but surprisingly when I click again on the emoticon list it refills the bounded textarea with emoticons unicode !! hope you got what I mean... And thanks in advance any ways ...

**Comment by ealush** [comment]
Hey, seems like you have a tiny mixup here.
Your textarea's value is probably bound to the state of the component. When you `document.getElementById('emoji').value=""`, you force the DOM element to be empty without actually changing the state. When there is another state update and a re-render that follows it, it is applied again on the textarea's value.

**Comment by torver213** [comment]
hello @ealush it is a great library you have worked on but please how do i convert your implementation to a functional component and still get the emojis display??? Again, how do i empty the value of the textarea after i must have sent the message because i'm using react hooks and i have tried something of this nature but it doesn't set the value of the textarea to empty. 
``` 
const [message, setMessage] = useState('')
 const handleClick = (e) =>{
    e.preventDefault();
    if(message) {
      socket.emit('sendMessage',(message),() =>{
    //**Here it is not setting the textarea empty after the message have been sent**
      setMessage('')
    })}
  }

  const handleChange = (e,value) =>{
    setMessage(value)
  }

  const handleKeyPress = (e,value) =>{
    if(e.key === 'Enter') {
      handleClick(e)}
  }

<EmojiField style={{borderRadius:30,resize: 'none',outline:'none',textAlign: '-webkit-center'}} name="my-textarea" maxLength={300} onKeyPress={handleKeyPress} value={message} onChange={handleChange} autoClose={true} className="write_msg" placeholder="Type a message"/>```
